### ISSUE TITLE
跳动的一个说法

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#10]
无法确定是以下读音中的哪一个：
zhueh7 zueh7 jyeh7

**Comment by HISAHARA** [comment]
jyeh7，[蹫](https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/j/jyeh.md#%E8%B9%AB)】

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/j/jyeh.md#%E8%B9%AB
