### ISSUE TITLE
疑难字 窗❔

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#104]
各地读音不同。窗bon、窗fon、窗mon。本字难考。

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/chuan_mon.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/chuan_fon.md

**Comment by UMIHEBI** [comment]
丹陽也是 窗mon
富陽那一圈那邊有 窗meen（和南同韻母）

**Comment by hqzxzwb** [comment]
维基收集了一个兴化的“窗蒙”
https://zh.m.wiktionary.org/zh-hans/%E7%AA%97%E6%88%B6

**Comment by hqzxzwb** [comment]
暂做窗蒙、窗封两写
