### ISSUE TITLE
粘

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#11]
dien1

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dien.md#%E9%92%89
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dien.md#%E5%8F%AE-1
需要确定一个字

**Comment by HISAHARA** [comment]
用 叮
