### ISSUE TITLE
兴化词典参考的《探奸遭陷》不知是何书，检索不到

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#111]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/chen_zhen.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/co_sheh.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/k/ken_qien.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/y/yen_li_v_li.md

**Comment by UMIHEBI** [comment]
水滸傳相關的。是不是戲曲劇本？

**Comment by hqzxzwb** [comment]
看起来是的。寻不到也无法了。

**Comment by hqzxzwb** [comment]
是《扬州评话选》中的
