### ISSUE TITLE
排疑 coh8

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#112]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/coh.md

1. 凿、簇两字，泰县读音异常。核实一下，是标错还是地方读音。
2. "叮：这荤菜不吃，摆啊那块～苍蝇。"释义不准。应并入“聚”义项。

**Comment by UMIHEBI** [comment]
镞

**Comment by hqzxzwb** [comment]
泰县coh7<刻>，coh8<聚>
