### ISSUE TITLE
疑音 当家

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#131]
目前收了一些dan ga的读音，翻阅词典并无dan ga读音记录。
如皋
<img width="346" alt="image" src="https://github.com/hqzxzwb/taerv_czdin_jihua/assets/5145108/a31aaf94-ec9a-411a-b640-d7a70a7fdf4d">
如东
<img width="574" alt="image" src="https://github.com/hqzxzwb/taerv_czdin_jihua/assets/5145108/053a80ba-5f71-41d4-9604-59c2e906b512">

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dan_ga.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dan_ga_cae_gah_shae_mi_guei_ian_er_cae_zhr_fv_mu_ngen.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dan_ga_dii.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dan_ga_fan_zhr_shae_mi_guei_ian_er_cae_bo_fv_mu_ngen.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dan_ga_li_shr.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dan_ga_ren.md

**Comment by hqzxzwb** [comment]
东台扫描版有【女当家】dan jia，【当家才觉柴米贵】dan ga。需核实。

**Comment by UMIHEBI** [comment]
家 这种字，组词本身就是文白都行的

**Comment by hqzxzwb** [comment]
暂按词典原文记音收录。东台歇后语注音需核实。

**Comment by hqzxzwb** [comment]
东台歇后语注音是生成的，不是原书记音
