### ISSUE TITLE
疑音 笤爪 

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#138]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/t/tio_zho.md
<img width="249" alt="image" src="https://github.com/hqzxzwb/taerv_czdin_jihua/assets/5145108/57522d3f-f6a9-4321-900b-1cea03139a03">

考虑是tio2 zhoh的音转。理由：
1. 泰如多数地区有后字变上声现象。
2. 泰县有后字舒化现象。
<img width="393" alt="image" src="https://github.com/hqzxzwb/taerv_czdin_jihua/assets/5145108/70a3e850-cac4-407d-8678-cb1d738b219b">

<img width="385" alt="image" src="https://github.com/hqzxzwb/taerv_czdin_jihua/assets/5145108/93748651-71c7-4ffe-8920-f2b899d81266">

3. 周边地区记音tio2 zhoh。
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/t/tio_zhoh.md

**Comment by UMIHEBI** [comment]
支持 苕竹。
ps：我们on/oh 变调，韵母也和o不一样，所以能区分不少
