### ISSUE TITLE
汤变得不粘稠

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#14]
盐城 xya5汤
泰兴 dien5汤

**Comment by osfans** [comment]
xya 北语用的澥，大概可以借用

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/dien_tan.md#%E6%BE%84%E6%B1%A4
已收录。用字反切不合且不统一。需要审字。
@HISAHARA
