### ISSUE TITLE
通过管子或小孔吸，吸食

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#21]
xieu2 - 泰兴 推导标准音 seu2 sheu2 xieu2
ceu2 - 大丰 推导标准音 ceu2 cheu2
考虑常母读音差异大，两处说法很可能同源。

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/46a5432712a7652ab1cc70ecfea664136bf9024f/c/cheu.md#%E4%8C%B7-2

**Comment by UMIHEBI** [comment]
这个字，可能是两个不同源的词在各地发生了不同的合并。cheu2的地区，是澄母字，抽/䌷 是符合的。sheu2的地区，可能是禅母字，或者是发生了和xieu的融合擦化。

**Comment by hqzxzwb** [comment]
找得到吗

**Comment by UMIHEBI** [comment]
一般就用 抽/䌷

**Comment by hqzxzwb** [comment]
那先关了
