### ISSUE TITLE
笃定某事一定会发生

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#26]
高港-gaeh7的

**Comment by hqzxzwb** [comment]
如东-ngeh8的，有兀的写法

**Comment by HISAHARA** [comment]
额的。

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/n/ngeh_dii.md#%E9%A2%9D%E7%9A%84
