### ISSUE TITLE
别的

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#30]
泰兴-geh7 sz

**Comment by HISAHARA** [comment]
各是？各事？
台州吴语说 各。

**Comment by hqzxzwb** [comment]
标音错了，确实是gah

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/s/sa.md#%E5%A1%9E
