### ISSUE TITLE
弯腰

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#37]
jyaen1

**Comment by hqzxzwb** [comment]
如东 son6

**Comment by HISAHARA** [comment]
有人说shon6

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/z/zhuaen.md#%E8%B7%A7

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/s/son.md
@HISAHARA 确认是翘舌音？改改

**Comment by HISAHARA** [comment]
改不了，我想新建一个shon词条，不能创建。
________________________________
发件人: hqzxzwb ***@***.***>
发送时间: 2024年4月14日 2:50
收件人: hqzxzwb/taerv_czdin_jihua ***@***.***>
抄送: HISAHARA ***@***.***>; Mention ***@***.***>
主题: Re: [hqzxzwb/taerv_czdin_jihua] 弯腰 (#37)


https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/s/son.md
@HISAHARA<https://github.com/HISAHARA> 确认是翘舌音？改改

―

**Comment by hqzxzwb** [comment]
用什么字？我来改
