### ISSUE TITLE
ngaen子

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#43]
除了钳子义外，指薏苡

**Comment by HISAHARA** [comment]
写 颜子 好了。要跟植物相关，可以借 楌 字。

**Comment by hqzxzwb** [comment]
钳子义已有字 上咸下齿
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/n/ngaen.md#%E4%B6%A0
