### ISSUE TITLE
搅拌

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#52]
泰兴lei3
推导标准音lei3，leu3，luei3，ly3

**Comment by gaozhiyan** [comment]
此字似可用攂（擂）代之，攂（擂）有研磨之义，似与搅拌的动作相似。只是攂的调类不合。

**Comment by HISAHARA** [comment]
吴语台州音柳

**Comment by hqzxzwb** [comment]
已确定
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/bieh.md#%E6%BB%97

**Comment by UMIHEBI** [comment]
> 已确定 https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/bieh.md#%E6%BB%97

啥意思？
