### ISSUE TITLE
表示贴近的hah

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#53]
现用字蠚
考虑下面这个字：
http://yedict.com/zsCONTENT.ASP?uni=25023

**Comment by gaozhiyan** [comment]
此字可考虑：攉
详见《汉语方言大词典》“攉”（p.7441)
义项2：用手人或物贴近（吴语）。。泰如的 hah, 当然不限于“用手”，而是泛指“贴近”，可视为语义的扩展。
![Capture](https://user-images.githubusercontent.com/14959235/94983797-17b2a300-0514-11eb-866c-6387a9ec408b.PNG)

**Comment by HISAHARA** [comment]
学皮那个匣母字。攉是huah7。在不知道本字的情况下，用同音字好一点。

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/h/hah.md
