### ISSUE TITLE
van6 𥭚，考虑“望”字

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#56]
“望砖”是常见写法。
相关：
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/baen_van_zhan.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/baen_van_qian.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/v/van_zhun.md

𥭚普通话音mang4。疑是吴语人根据白读maon找的字。据泰如读音，“望砖”首字应当是一个官话中已经轻唇化的字。

**Comment by HISAHARA** [comment]
障𥭚，经常说，小时候常见。感觉𥭚的意思对得上。发音的确不合。望的话，意思对不上。

**Comment by hqzxzwb** [comment]
没能找到𥭚的释义。可否附链接？

**Comment by HISAHARA** [comment]
汉典。https://www.zdic.net/hans/%F0%A5%AD%9A
簀的意思是竹編床席。
障van，就是芦席之类的东西。

**Comment by hqzxzwb** [comment]
了解。定𥭚字吧。
