### ISSUE TITLE
ban1 <附着>，存在多字，需要确定

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#57]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/ban.md
帮、傍两种写法。

以及，ban1<将近>是否同一字？

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/ban_heh.md

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/ban_qieh.md

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/ban_un_r.md

**Comment by hqzxzwb** [comment]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/ban_v.md

**Comment by HISAHARA** [comment]
感觉帮和傍都被普通话用的太固定了。普通话的释义里，帮傍都有靠近的意思。帮黑，帮暗，感觉会误解，现在用傍，又担心读错字。

**Comment by hqzxzwb** [comment]
从前傍晚读bāng吗？好像淘汰掉了

**Comment by HISAHARA** [comment]
汉典上写的，台湾的国语词典还是阴平。
________________________________
发件人: hqzxzwb ***@***.***>
发送时间: 2024年4月14日 3:01
收件人: hqzxzwb/taerv_czdin_jihua ***@***.***>
抄送: HISAHARA ***@***.***>; Comment ***@***.***>
主题: Re: [hqzxzwb/taerv_czdin_jihua] ban1 <附着>，存在多字，需要确定 (Issue #57)


从前傍晚读bāng吗？好像淘汰掉了

―

**Comment by hqzxzwb** [comment]
按习惯来吧，空间用“帮”，时间用“傍”。

**Comment by hqzxzwb** [comment]
那好像都写的对的
