### ISSUE TITLE
泼水

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#6]
如东 vaeh8

**Comment by gaozhiyan** [comment]
這個字是 【敌】（注意，不是敵）
【敌】《集韻》乎刮切,音頢。盡也。本義是用舌頭舔盡。引申爲“全部”之意。
敌水，即使水倒盡。

另，南通方言中，敌 可作副詞，表示全部。敌來了，即表示都來了
