### ISSUE TITLE
排疑-壁滑

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#61]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/bieh_hua.md

滑无hua2音

另外，
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/b/bieh_huaeh.md
壁、笔选一个字。推荐壁。

**Comment by HISAHARA** [comment]
要删掉第一个，现在改版了，我找不到删除按钮。
