### ISSUE TITLE
排疑 - 着躁

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#67]
标注读音 chah8 zo5

实际知晓的音折合 zhah7 zo5。

需要核实 chah8 zo5 读音来源。

**Comment by HISAHARA** [comment]
根据兴化词典注音阳入。如果是阴入，就要写“作躁”。还有“着闷气”也是，如果是阴入，也要写“作”。

**Comment by HISAHARA** [comment]
![image](https://github.com/hqzxzwb/taerv_czdin_jihua/assets/53264783/aac3aa37-8f91-4419-b4fa-f72c1ae4181d)
![QQ截图20240406220426](https://github.com/hqzxzwb/taerv_czdin_jihua/assets/53264783/4a442a2f-8d13-449c-b7ae-feb945f736fd)
