### ISSUE TITLE
排疑 直像

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#68]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/cheh_qian.md

> 好像：你看他～的忙煞咖。

释义代入到例句中，牵强。
疑与[直将](https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/cheh_jian.md)是同一个词。

**Comment by HISAHARA** [comment]
已改

**Comment by UMIHEBI** [comment]
男將女將的將，我們也送氣。有可能
