### ISSUE TITLE
排疑 pon6/1

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#76]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/c/cho_a_pon_qi_lae_a.md
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/p/pon.md#%E4%B3%9E

两处应为同一字。释义“笑”，可疑。

**Comment by HISAHARA** [comment]
已改。
