### ISSUE TITLE
排疑 大人<长辈>读音

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#83]
知晓tu6 ren2读音，词典内未标注，而是放在da6 ren音之下。
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/da_ren.md
是地区差异还是漏标？

**Comment by HISAHARA** [comment]
tu6 ren2没有收的话，加一下好了，如东如皋是说da ren。

**Comment by hqzxzwb** [comment]
是泰兴的。等什么时候加入泰兴词典，应该能收到。

**Comment by HISAHARA** [comment]
没有专业的泰兴词典。网上买到的泰兴词典只有汉字，没有注音，不敢整理进去。
________________________________
发件人: hqzxzwb ***@***.***>
发送时间: 2024年4月10日 10:06
收件人: hqzxzwb/taerv_czdin_jihua ***@***.***>
抄送: HISAHARA ***@***.***>; Comment ***@***.***>
主题: Re: [hqzxzwb/taerv_czdin_jihua] 排疑 大人<长辈>读音 (Issue #83)


是泰兴的。等什么时候加入泰兴词典，应该能收到。

―

**Comment by UMIHEBI** [comment]
> 话说tu6 ren2是哪里的说法？收的时候最好注明一下。或者你来加？

tu6人是長輩，da6人是成年人、官員
