### ISSUE TITLE
疑难字 打□子笑

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#85]
https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/d/da_vah_zz_xio.md

**Comment by HISAHARA** [comment]
写嗀吧。

xian_ly_vah_xin.md
这个怎么删除词条

**Comment by hqzxzwb** [comment]
[㗥 kuah8](https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/k/kuah.md#%E3%97%A5)
如皋匣母读群母，如东匣母丢失。

**Comment by hqzxzwb** [comment]
对照huah闪，如东阴入，其他地区阳入，部分地区读vah8。平行的语音现象。

**Comment by hqzxzwb** [comment]
> 对照huah闪，如东阴入，其他地区阳入，部分地区读vah8。平行的语音现象。 https://github.com/hqzxzwb/taerv_czdin_jihua/blob/master/h/huah_shin.md 核实一下这里兴化泰县的词典是阴入还是阳入。

泰县阳入，兴化阴入
