### ISSUE TITLE
排疑 半吊子

### ISSUE THREAD

**Issue by hqzxzwb** [hqzxzwb/taerv_czdin_jihua#90]
# 半吊子
bun5 dio5 zz
> 兴化方言词典
- 不够朋友，不讲交情的人：朋友之间总要顾点情面，不要当～。｜我说的嘛，不能全做～，总有个把朋友的唦。（扬二：《朱元球颞贩卖乌梅》）

书名不正确。不知道是什么书。目测是朱元璋卖乌梅之类的。

**Comment by HISAHARA** [comment]
已改。
